defmodule EvenglassWeb.Api.AuthController do
  @moduledoc """
  Hub App authentication endpoints.

    * `POST /api/g2/enroll`        — Public. Exchange a single-use enrollment_code
                                     for a device_token (90d).
    * `POST /api/g2/refresh`       — Authenticated. Sliding renewal: trade current
                                     device_token for a fresh one with a rotated
                                     `jti`. Old token effectively revoked.
    * `GET  /api/g2/whoami`        — Authenticated. Returns device metadata.
    * `POST /api/g2/socket-token`  — Authenticated. Issues a 2h channel_token
                                     for WSS connect.

  Authenticated routes go through `EvenglassWeb.Plugs.AuthenticatedAPI` which
  verifies the Bearer device_token and assigns `:device` and `:device_id`.
  """

  use EvenglassWeb, :controller
  use OpenApiSpex.ControllerSpecs

  alias Evenglass.Auth.Token
  alias Evenglass.Devices

  alias EvenglassWeb.Schemas.{
    EnrollRequest,
    EnrollResponse,
    ErrorResponse,
    RefreshResponse,
    SocketTokenResponse,
    WhoamiResponse
  }

  tags(["g2-auth"])

  ## Public ──────────────────────────────────────────────────────────────────

  operation(:enroll,
    summary: "Exchange a single-use enrollment code for a device token",
    description: """
    First call from a Hub App. The 6-digit code is generated by an admin via
    `/admin/devices/new` and is valid for 10 minutes. Rate-limited 5/min/IP.
    """,
    request_body: {"Enrollment code", "application/json", EnrollRequest},
    responses: %{
      201 => {"Enrolled — keep the device_token", "application/json", EnrollResponse},
      400 => {"Malformed body", "application/json", ErrorResponse},
      401 => {"Code invalid/expired or serial mismatch", "application/json", ErrorResponse},
      429 => {"Per-IP rate limit (5/min) hit", "application/json", ErrorResponse}
    }
  )

  def enroll(conn, %{"code" => code} = params) when is_binary(code) do
    glasses_serial = params["glasses_serial"]

    case Devices.consume_enrollment_code(code, glasses_serial) do
      {:ok, device} ->
        jti = generate_jti()
        device = Devices.set_jti!(device, jti)
        token = Token.sign_device_token(%{device_id: device.id, jti: jti})

        conn
        |> put_status(:created)
        |> json(%{
          device_id: device.id,
          device_token: token,
          expires_in: Token.device_max_age()
        })

      {:error, :invalid_or_expired} ->
        reject(conn, "invalid_or_expired_code")

      {:error, :glasses_serial_mismatch} ->
        reject(conn, "glasses_serial_mismatch")
    end
  end

  def enroll(conn, _params) do
    conn
    |> put_status(:bad_request)
    |> json(%{error: "code (string) is required"})
  end

  ## Authenticated ───────────────────────────────────────────────────────────

  operation(:refresh,
    summary: "Sliding renewal of the device token",
    description: """
    Trades the current `device_token` for a fresh one with a rotated `jti`.
    The old token is implicitly revoked because its `jti` no longer matches
    what the server has stored.
    """,
    security: [%{"BearerAuth" => []}],
    responses: %{
      200 => {"New token issued", "application/json", RefreshResponse},
      401 => {"Old token invalid/expired/revoked", "application/json", ErrorResponse}
    }
  )

  def refresh(%{assigns: %{device: device}} = conn, _params) do
    new_jti = generate_jti()
    device = Devices.set_jti!(device, new_jti)
    new_token = Token.sign_device_token(%{device_id: device.id, jti: new_jti})

    json(conn, %{
      device_token: new_token,
      expires_in: Token.device_max_age()
    })
  end

  operation(:whoami,
    summary: "Returns metadata for the bearer-authenticated device",
    security: [%{"BearerAuth" => []}],
    responses: %{
      200 => {"Device metadata", "application/json", WhoamiResponse},
      401 => {"Bearer missing/invalid", "application/json", ErrorResponse}
    }
  )

  def whoami(%{assigns: %{device: device}} = conn, _params) do
    json(conn, %{
      device_id: device.id,
      glasses_serial: device.glasses_serial,
      last_seen_at: device.last_seen_at
    })
  end

  operation(:socket_token,
    summary: "Issues a 2-hour channel token for WSS connect",
    description: """
    Hub App calls this just before opening `wss://.../socket?token=<channel_token>`.
    Channel join authorization (`g2:device:<id>`) requires the token's
    `device_id` to equal the topic's device_id.
    """,
    security: [%{"BearerAuth" => []}],
    responses: %{
      200 => {"Channel token issued", "application/json", SocketTokenResponse},
      401 => {"Bearer missing/invalid", "application/json", ErrorResponse}
    }
  )

  def socket_token(%{assigns: %{device: device}} = conn, _params) do
    ct = Token.sign_channel_token(%{device_id: device.id, role: :device})

    json(conn, %{
      channel_token: ct,
      expires_in: Token.channel_max_age()
    })
  end

  ## Helpers ─────────────────────────────────────────────────────────────────

  defp reject(conn, reason) do
    conn
    |> put_status(:unauthorized)
    |> json(%{error: reason})
  end

  defp generate_jti do
    16
    |> :crypto.strong_rand_bytes()
    |> Base.url_encode64(padding: false)
  end
end
